version: '3.1'
services:
  database:
    image: mysql
    container_name: mysql
    volumes:
      - ecommerce:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  ecommerce: